services:
  frontend:
    build: client
    image: suryakn/electrum-frontend-prod:newaws
    ports:
      - 5173:5173
    networks:
      - electrum
    depends_on:
      - backend

  backend:
    build: server
    image: suryakn/electrum-backend-prod:newaws
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/electrumDB
      - REDIS_URL=redis-db:6379
    networks:
      - electrum
    depends_on:
      db:
        condition: service_healthy
      redis-db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - electrum
    environment:
      - POSTGRES_DB=electrumDB
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d electrumDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis-db:
    image: redis
    restart: always
    networks:
      - electrum
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
networks:
  electrum:
